# Generated by Django 2.0.7 on 2018-07-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignaturas',
        ),
    ]
