# Generated by Django 2.0.7 on 2018-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_delete_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='chat_text',
            field=models.TextField(default='Habla con tu profesor por este chat.'),
        ),
    ]
